/**
 * VMDR endpoints.
 *
 * The Qualys platform API: detections, hosts, scan scope, scans and search lists.
 *
 * Everything here is data: which endpoint an operation calls, how its response
 * is shaped and which UI parameters it shows. The router reads these fields
 * rather than branching on the resource name, so adding an endpoint is an entry
 * in this table and nothing else.
 */
import { list, type ResourceDefinition } from '../definition';

export const vmdrResource: ResourceDefinition = {
  name: 'VMDR',
  description:
    'Vulnerability Management, Detection and Response: detections, hosts, scan scope, scans and search lists',
  operations: {
    listDetections: list({
      name: 'List Detections',
      action: 'List vulnerability detections',
      description: 'Per-host detections with Qualys Detection Scores',
      plane: 'fo',
      endpoint: '/api/5.0/fo/asset/host/vm/detection/',
      xml: true,
      apiAction: 'list',
      recordPath: 'HOST_LIST_VM_DETECTION_OUTPUT.RESPONSE.HOST_LIST.HOST',
      optionsProperty: 'detectionOptions',
      truncatable: true,
    }),
    listKnowledgeBase: list({
      name: 'List KnowledgeBase',
      action: 'List KnowledgeBase entries',
      description: 'QID metadata: description, threat, solution, CVEs',
      plane: 'fo',
      endpoint: '/api/4.0/fo/knowledge_base/vuln/',
      xml: true,
      apiAction: 'list',
      recordPath: 'KNOWLEDGE_BASE_VULN_LIST_OUTPUT.RESPONSE.VULN_LIST.VULN',
      optionsProperty: 'knowledgeBaseOptions',
    }),
    listCveScores: list({
      name: 'List CVE Scores',
      action: 'List CVE risk scores',
      description: 'Qualys Vulnerability Score per CVE',
      plane: 'fo',
      endpoint: '/api/2.0/fo/knowledge_base/qvs/',
      apiAction: 'list',
      keyedRecords: 'cve',
      optionsProperty: 'cveScoreOptions',
    }),
    listHosts: list({
      name: 'List Hosts',
      action: 'List scanned hosts',
      description: 'Scanned hosts with TruRisk scores',
      plane: 'fo',
      endpoint: '/api/5.0/fo/asset/host/',
      xml: true,
      apiAction: 'list',
      recordPath: 'HOST_LIST_OUTPUT.RESPONSE.HOST_LIST.HOST',
      optionsProperty: 'hostOptions',
      truncatable: true,
    }),
    listVirtualHosts: list({
      name: 'List Virtual Hosts',
      action: 'List virtual hosts',
      description: 'Virtual host configuration',
      plane: 'fo',
      endpoint: '/api/2.0/fo/asset/vhost/',
      xml: true,
      apiAction: 'list',
      recordPath: 'VIRTUAL_HOST_LIST_OUTPUT.RESPONSE.VIRTUAL_HOST_LIST.VHOST',
    }),
    listAssetGroups: list({
      name: 'List Asset Groups',
      action: 'List asset groups',
      description: 'Asset groups and their members',
      plane: 'fo',
      endpoint: '/api/2.0/fo/asset/group/',
      xml: true,
      apiAction: 'list',
      recordPath: 'ASSET_GROUP_LIST_OUTPUT.RESPONSE.ASSET_GROUP_LIST.ASSET_GROUP',
      optionsProperty: 'assetGroupOptions',
      truncatable: true,
    }),
    listNetworks: list({
      name: 'List Networks',
      action: 'List networks',
      description: 'Custom networks, when network support is enabled',
      plane: 'fo',
      endpoint: '/api/2.0/fo/network/',
      xml: true,
      apiAction: 'list',
      recordPath: 'NETWORK_LIST_OUTPUT.RESPONSE.NETWORK_LIST.NETWORK',
    }),
    listDomains: list({
      name: 'List Domains',
      action: 'List domains',
      description: 'Domains registered in the subscription',
      plane: 'fo',
      endpoint: '/api/2.0/fo/asset/domain/',
      xml: true,
      apiAction: 'list',
      // This endpoint answers without the usual _OUTPUT/RESPONSE envelope.
      recordPath: 'DOMAIN_LIST.DOMAIN',
    }),
    listIpAddresses: list({
      name: 'List IP Addresses',
      action: 'List IP addresses',
      description: 'Addresses and ranges in the subscription',
      plane: 'fo',
      endpoint: '/api/2.0/fo/asset/ip/',
      xml: true,
      apiAction: 'list',
      // IP_SET carries bare addresses and ranges side by side, so it is
      // emitted whole rather than split into heterogeneous items.
      recordPath: 'IP_LIST_OUTPUT.RESPONSE.IP_SET',
      optionsProperty: 'ipOptions',
    }),
    listExcludedHosts: list({
      name: 'List Excluded Hosts',
      action: 'List excluded hosts',
      description: 'Hosts excluded from scanning',
      plane: 'fo',
      endpoint: '/api/2.0/fo/asset/excluded_ip/',
      xml: true,
      apiAction: 'list',
      recordPath: 'IP_LIST_OUTPUT.RESPONSE.IP_SET',
    }),
    listScans: list({
      name: 'List Scans',
      action: 'List scans',
      description: 'Scan history and status',
      plane: 'fo',
      endpoint: '/api/2.0/fo/scan/',
      xml: true,
      apiAction: 'list',
      recordPath: 'SCAN_LIST_OUTPUT.RESPONSE.SCAN_LIST.SCAN',
      optionsProperty: 'scanOptions',
    }),
    listAppliances: list({
      name: 'List Scanner Appliances',
      action: 'List scanner appliances',
      description: 'Scanner appliances and their status',
      plane: 'fo',
      endpoint: '/api/2.0/fo/appliance/',
      xml: true,
      apiAction: 'list',
      recordPath: 'APPLIANCE_LIST_OUTPUT.RESPONSE.APPLIANCE_LIST.APPLIANCE',
    }),
    listReports: list({
      name: 'List Reports',
      action: 'List reports',
      description: 'Generated reports and their status',
      plane: 'fo',
      endpoint: '/api/3.0/fo/report/',
      xml: true,
      apiAction: 'list',
      recordPath: 'REPORT_LIST_OUTPUT.RESPONSE.REPORT_LIST.REPORT',
      optionsProperty: 'reportOptions',
    }),
    listStaticSearchLists: list({
      name: 'List Static Search Lists',
      action: 'List static search lists',
      description: 'Search lists with a fixed set of QIDs',
      plane: 'fo',
      endpoint: '/api/2.0/fo/qid/search_list/static/',
      xml: true,
      apiAction: 'list',
      recordPath: 'STATIC_SEARCH_LIST_OUTPUT.RESPONSE.STATIC_LISTS.STATIC_LIST',
      optionsProperty: 'searchListOptions',
    }),
    listDynamicSearchLists: list({
      name: 'List Dynamic Search Lists',
      action: 'List dynamic search lists',
      description:
        'Search lists built from a query. Qualys evaluates these server side and they can be slow.',
      plane: 'fo',
      endpoint: '/api/3.0/fo/qid/search_list/dynamic/',
      xml: true,
      apiAction: 'list',
      recordPath: 'DYNAMIC_SEARCH_LIST_OUTPUT.RESPONSE.DYNAMIC_LISTS.DYNAMIC_LIST',
      optionsProperty: 'searchListOptions',
    }),
  },
};
